N-dimensional arrays in NumPy are only compatible with values of the same data type.

Arrays can organize values into matrices and vectors.

One-dimensional arrays are called vectors
Multi-dimensional arrays are called matrices

In [1]:
import numpy as np


In [2]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a)
print(a.shape)
print(a[0,2])

[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
2


In [3]:
a[1,3] = 8
a[1,3]

8

Generating random numbers is useful to run simulations of data entries.
Firstly, one must import the random module

    >>> import random

    • random.random() - generates a float value in range [0,1)

    • random.randit(min, max) - generates an integer value in the provided interval [min, max].

To combine NumPy and random module, one must concatenate the numpy and random operators one after the other.

i.e.

    Create a matrix of n rows and n columns using randomized integer values

    >>> import numpy as np
    >>> import random

    >>> np.random.randit(1, 9, (n,n))

In [4]:
import random

rand_float = random.random()

print(rand_float)

rand_int = random.randint(29, 38)

print(rand_int)

rand_matrix = np.random.randint(1,6, (4,6))

print(rand_matrix)

0.41985558437120696
29
[[3 3 2 3 2 4]
 [3 1 5 1 5 1]
 [5 5 2 1 2 3]
 [5 4 1 3 1 5]]


In [5]:
import pandas as pd

ser = pd.Series(np.random.random(5), name = "Column: 01")
print(ser)

0    0.589499
1    0.833780
2    0.200109
3    0.376938
4    0.612500
Name: Column: 01, dtype: float64


In [6]:
from pandas_datareader import data as wb

Apple = wb.DataReader('AAPL', data_source = 'yahoo', start = '1995-1-1')

TSLA = wb.DataReader('TSLA', data_source='yahoo', start='2012-1-1')

print(TSLA.head(20)['Adj Close'])


Date
2012-01-03    5.616
2012-01-04    5.542
2012-01-05    5.424
2012-01-06    5.382
2012-01-09    5.450
2012-01-10    5.524
2012-01-11    5.646
2012-01-12    5.650
2012-01-13    4.558
2012-01-17    5.320
2012-01-18    5.362
2012-01-19    5.352
2012-01-20    5.320
2012-01-23    5.354
2012-01-24    5.484
2012-01-25    5.594
2012-01-26    5.788
2012-01-27    5.866
2012-01-30    5.914
2012-01-31    5.814
Name: Adj Close, dtype: float64


In [7]:
Apple.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6919 entries, 1995-01-03 to 2022-06-24
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   High       6919 non-null   float64
 1   Low        6919 non-null   float64
 2   Open       6919 non-null   float64
 3   Close      6919 non-null   float64
 4   Volume     6919 non-null   float64
 5   Adj Close  6919 non-null   float64
dtypes: float64(6)
memory usage: 378.4 KB


In [8]:
# To see first n rows of data use obj.head(n)
# If no n argument is given, the function automatically presents the first 5 rows

Apple.head(30)

High       Low      Open     Close        Volume  Adj Close
Date                                                                       
1995-01-03  0.347098  0.338170  0.347098  0.342634  1.038688e+08   0.289652
1995-01-04  0.353795  0.344866  0.344866  0.351563  1.586816e+08   0.297200
1995-01-05  0.351563  0.345982  0.350446  0.347098  7.364000e+07   0.293425
1995-01-06  0.385045  0.367188  0.371652  0.375000  1.076622e+09   0.317013
1995-01-09  0.373884  0.366071  0.371652  0.367885  2.740864e+08   0.310998
1995-01-10  0.392857  0.368304  0.368304  0.390067  6.147904e+08   0.329750
1995-01-11  0.429129  0.381138  0.390625  0.417411  8.738240e+08   0.352866
1995-01-12  0.414063  0.399554  0.411830  0.405134  5.517792e+08   0.342487
1995-01-13  0.411830  0.396205  0.411830  0.400670  3.513776e+08   0.338713
1995-01-16  0.404018  0.395089  0.400670  0.397321  1.889776e+08   0.335882
1995-01-17  0.406250  0.393973  0.397321  0.401786  3.301088e+08   0.339657
1995-01-18  0.407366  0.399554  0.401786  0.407366  1.276576e+08   0.344374
1995-01-19  0.410714  0.401786  0.406250  0.409598  3.142944e+08   0.346261
1995-01-20  0.419643  0.379464  0.419643  0.380580  1.000362e+09   0.321730
1995-01-23  0.380580  0.366071  0.373884  0.377232  3.985408e+08   0.318900
1995-01-24  0.378348  0.369420  0.377232  0.371652  2.180976e+08   0.314182
1995-01-25  0.375000  0.352679  0.352679  0.365932  5.170704e+08   0.309347
1995-01-26  0.370536  0.350446  0.364955  0.352679  2.463888e+08   0.298143
1995-01-27  0.360491  0.348214  0.356027  0.356027  2.985696e+08   0.300974
1995-01-30  0.361607  0.356027  0.358259  0.358259  2.305856e+08   0.302860
1995-01-31  0.364955  0.357143  0.361607  0.360491  2.127776e+08   0.304747
1995-02-01  0.363839  0.356027  0.363839  0.358259  1.583680e+08   0.302860
1995-02-02  0.373884  0.358259  0.358259  0.371652  2.035824e+08   0.314182
1995-02-03  0.376116  0.360491  0.375000  0.361607  3.192112e+08   0.305691
1995-02-06  0.363839  0.352679  0.363839  0.361607  2.430288e+08   0.305691
1995-02-07  0.366071  0.357143  0.360491  0.364397  2.016000e+08   0.308049
1995-02-08  0.378348  0.364955  0.366071  0.377790  4.028640e+08   0.319371
1995-02-09  0.391741  0.376116  0.376116  0.389509  4.753952e+08   0.329278
1995-02-10  0.394531  0.387277  0.389509  0.390625  3.509632e+08   0.330222
1995-02-13  0.397321  0.386161  0.388393  0.390625  2.833712e+08   0.331130

In [9]:
# To see last n rows of obj, use obj.tail(n)
# If no n argument is given, the function automatically presents the last 5 rows


Apple.tail(30)

High         Low        Open       Close       Volume  \
Date                                                                      
2022-05-12  146.199997  138.800003  142.770004  142.559998  182602000.0   
2022-05-13  148.100006  143.110001  144.589996  147.110001  113990900.0   
2022-05-16  147.520004  144.179993  145.550003  145.539993   86643800.0   
2022-05-17  149.770004  146.679993  148.860001  149.240005   78336300.0   
2022-05-18  147.360001  139.899994  146.850006  140.820007  109742900.0   
2022-05-19  141.660004  136.600006  139.880005  137.350006  136095600.0   
2022-05-20  140.699997  132.610001  139.089996  137.589996  137426100.0   
2022-05-23  143.259995  137.649994  137.789993  143.110001  117726300.0   
2022-05-24  141.970001  137.330002  140.809998  140.360001  104132700.0   
2022-05-25  141.789993  138.339996  138.429993  140.520004   92482700.0   
2022-05-26  144.339996  137.139999  137.389999  143.779999   90601500.0   
2022-05-27  149.679993  145.259995  145.389999  149.639999   90978500.0   
2022-05-31  150.660004  146.839996  149.070007  148.839996  103718400.0   
2022-06-01  151.740005  147.679993  149.899994  148.710007   74286600.0   
2022-06-02  151.270004  146.860001  147.830002  151.210007   72348100.0   
2022-06-03  147.970001  144.460007  146.899994  145.380005   88471400.0   
2022-06-06  148.570007  144.899994  147.029999  146.139999   71598400.0   
2022-06-07  149.000000  144.100006  144.350006  148.710007   67808200.0   
2022-06-08  149.869995  147.460007  148.580002  147.960007   53950200.0   
2022-06-09  147.949997  142.529999  147.080002  142.639999   69473000.0   
2022-06-10  140.759995  137.059998  140.279999  137.130005   91437900.0   
2022-06-13  135.199997  131.440002  132.869995  131.880005  122207100.0   
2022-06-14  133.889999  131.479996  133.130005  132.759995   84784300.0   
2022-06-15  137.339996  132.160004  134.289993  135.429993   91533000.0   
2022-06-16  132.389999  129.039993  132.080002  130.059998  108123900.0   
2022-06-17  133.080002  129.809998  130.070007  131.559998  134118500.0   
2022-06-21  137.059998  133.320007  133.419998  135.869995   81000500.0   
2022-06-22  137.759995  133.910004  134.789993  135.350006   73409200.0   
2022-06-23  138.589996  135.630005  136.820007  138.270004   72433800.0   
2022-06-24  141.910004  139.770004  139.899994  141.660004   89047400.0   

             Adj Close  
Date                    
2022-05-12  142.559998  
2022-05-13  147.110001  
2022-05-16  145.539993  
2022-05-17  149.240005  
2022-05-18  140.820007  
2022-05-19  137.350006  
2022-05-20  137.589996  
2022-05-23  143.110001  
2022-05-24  140.360001  
2022-05-25  140.520004  
2022-05-26  143.779999  
2022-05-27  149.639999  
2022-05-31  148.839996  
2022-06-01  148.710007  
2022-06-02  151.210007  
2022-06-03  145.380005  
2022-06-06  146.139999  
2022-06-07  148.710007  
2022-06-08  147.960007  
2022-06-09  142.639999  
2022-06-10  137.130005  
2022-06-13  131.880005  
2022-06-14  132.759995  
2022-06-15  135.429993  
2022-06-16  130.059998  
2022-06-17  131.559998  
2022-06-21  135.869995  
2022-06-22  135.350006  
2022-06-23  138.270004  
2022-06-24  141.660004

To represent data in pandas, one can use a dataframe with the method:
    
    • DataFrame() - Creates an object of type dataframe with columns of data.

    >>> new_data = np.DataFrame()

Note: a DataFrame essentially works as a dictionary in the sense that every column is a key with its values. To create key-value pairs in the data frame, one can use the same methods for regular dictionaries:

    • dataframe[key] = data - Adds a key-value pair to the DataFrame
    • One can gather specific data by using key values with DataReader. 
    I.E. wb.DataReader()[Key]


    >>> new_data['TSLA'] = wb.DataReader('TSLA', data_source='yahoo', start='2012-1-1')['Adj Close']

In [10]:
tickers = ['PG', 'MSFT', 'T', 'F', 'GE']
new_data = pd.DataFrame()

for t in tickers:
    new_data[t] = wb.DataReader(t, data_source='yahoo', start='1995-1-1')['Adj Close']

In [11]:
new_data.tail(20)

PG        MSFT          T      F         GE
Date                                                           
2022-05-26  146.479996  265.899994  21.320000  13.12  77.010002
2022-05-27  148.720001  273.239990  21.290001  13.63  78.760002
2022-05-31  147.880005  271.869995  21.290001  13.68  78.290001
2022-06-01  145.639999  272.420013  21.219999  13.55  77.519997
2022-06-02  147.210007  274.579987  21.190001  13.89  78.000000
2022-06-03  145.889999  270.019989  20.900000  13.50  76.970001
2022-06-06  145.320007  268.750000  20.940001  13.46  77.000000
2022-06-07  146.940002  272.500000  21.139999  13.74  78.000000
2022-06-08  145.110001  270.410004  21.049999  13.53  77.160004
2022-06-09  142.490005  264.790009  20.879999  13.28  74.779999
2022-06-10  141.949997  252.990005  20.690001  12.75  71.230003
2022-06-13  138.149994  242.259995  19.760000  11.81  67.720001
2022-06-14  133.839996  244.490005  19.450001  12.20  68.050003
2022-06-15  132.509995  251.759995  19.440001  12.27  69.099998
2022-06-16  133.320007  244.970001  18.959999  11.25  65.290001
2022-06-17  132.360001  247.649994  19.379999  11.23  66.000000
2022-06-21  136.369995  253.740005  19.959999  11.46  65.750000
2022-06-22  138.500000  253.130005  20.320000  11.48  64.540001
2022-06-23  142.300003  258.859985  20.610001  11.56  64.070000
2022-06-24  144.350006  267.700012  20.990000  12.01  67.080002

Using Quandl to gather data:

>>> import quandl 

    • quandl.get() - fetches information from the argument specified in the get method

i.e.
>>> quandl.get('FRED/GDP')

    The get method gathers data from the Federal Reserve Economic Data with regards to GDP

In [12]:
import quandl
data_01 = quandl.get('FRED/GDP')
data_01

Value
Date                 
1947-01-01    243.164
1947-04-01    245.968
1947-07-01    249.585
1947-10-01    259.745
1948-01-01    265.742
...               ...
2020-10-01  21477.597
2021-01-01  22038.226
2021-04-01  22740.959
2021-07-01  23202.344
2021-10-01  23992.355

[300 rows x 1 columns]

One can convert data to a comma-separated-value file by applying the following method to the variable specified in code.

    • to_csv(path) - Using the to_csv method converts a data setr to a CSV file. One must also specify in the argument the destination (path) and name of the file.

>>>data_01.to_csv(C:\Users\Python for Finance\---NAME OF YOUR FILE---)

To read the csv file, use the following method:

    • pd.read_csv(path) - This allows panda to read the csv file in python.

Alternatively, one could also convert the data to an excel file by replacing the 'csv' part of the method with 'excel'
    
    • to_excel(path)
    • pd.read_excel(path)

In [13]:
data_01.to_csv(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.csv')
data_02 = pd.read_csv(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.csv')

In [14]:
print(data_02.head(5))
print(data_02.tail(5))

         Date    Value
0  1947-01-01  243.164
1  1947-04-01  245.968
2  1947-07-01  249.585
3  1947-10-01  259.745
4  1948-01-01  265.742
           Date      Value
295  2020-10-01  21477.597
296  2021-01-01  22038.226
297  2021-04-01  22740.959
298  2021-07-01  23202.344
299  2021-10-01  23992.355


In [15]:
data_02.to_excel(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.xlsx', index=False)
data_03 = pd.read_excel(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.xlsx')

In [16]:
data_03.head(5)

Date    Value
0  1947-01-01  243.164
1  1947-04-01  245.968
2  1947-07-01  249.585
3  1947-10-01  259.745
4  1948-01-01  265.742

In [17]:
data_03.tail(5)

Date      Value
295  2020-10-01  21477.597
296  2021-01-01  22038.226
297  2021-04-01  22740.959
298  2021-07-01  23202.344
299  2021-10-01  23992.355

Python will, by default, assign python indexing (default integer index) to the data we provide. That is to say, data is not sorted by any other metric, but rather from 0 onwards. 

To change this, one can include another argument in the read method:

    • pd.read_excel/csv(path, index_col="") - To change the indexing, one must specify, within quotation marks, the key column from which the indeces will be extracted.

>>> pd.read_excel(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.xlsx', index_col='Date')

Another method for changing the index:

    • data_03.set_index('index') - after a data type variable is already defined, one can set an index that stems from the data set itself. This is done by passing the desired index in the argument within quotation marks/apostrophes.

    However, there is one caveat to this method. It will only display the data associated with the index

In [18]:
new_data03 = pd.read_excel(r'C:\Users\infin\OneDrive\Documentos\Python for Finance\my_data01.xlsx', index_col='Date')
new_data03

Value
Date                 
1947-01-01    243.164
1947-04-01    245.968
1947-07-01    249.585
1947-10-01    259.745
1948-01-01    265.742
...               ...
2020-10-01  21477.597
2021-01-01  22038.226
2021-04-01  22740.959
2021-07-01  23202.344
2021-10-01  23992.355

[300 rows x 1 columns]

In [19]:
data_02.set_index('Date')

Value
Date                 
1947-01-01    243.164
1947-04-01    245.968
1947-07-01    249.585
1947-10-01    259.745
1948-01-01    265.742
...               ...
2020-10-01  21477.597
2021-01-01  22038.226
2021-04-01  22740.959
2021-07-01  23202.344
2021-10-01  23992.355

[300 rows x 1 columns]