N-dimensional arrays in NumPy are only compatible with values of the same data type.

Arrays can organize values into matrices and vectors.

One-dimensional arrays are called vectors
Multi-dimensional arrays are called matrices

In [3]:
import numpy as np


In [13]:
a = np.array([[0,1,2,3],[4,5,6,7]])
print(a)
a.shape
print(a[0,2])

[[0 1 2 3]
 [4 5 6 7]]
2


In [15]:
a[1,3] = 8
a[1,3]

8

Generating random numbers is useful to run simulations of data entries.
Firstly, one must import the random module

    >>> import random

    • random.random() - generates a float value in range [0,1)

    • random.randit(min, max) - generates an integer value in the provided interval [min, max].

To combine NumPy and random module, one must concatenate the numpy and random operators one after the other.

i.e.

    Create a matrix of n rows and n columns using randomized integer values

    >>> import numpy as np
    >>> import random

    >>> np.random.randit(1, 9, (n,n))

In [44]:
import random

rand_float = random.random()

print(rand_float)

rand_int = random.randint(29, 38)

print(rand_int)

rand_matrix = np.random.randint(1,6, (4,6))

print(rand_matrix)

0.4193905709146264
31
[[2 3 2 3 3 4]
 [3 3 4 5 1 2]
 [3 4 4 3 4 2]
 [3 2 2 5 1 2]]


In [46]:
import pandas as pd

ser = pd.Series(np.random.random(5), name = "Column: 01")
ser

0    0.895534
1    0.656404
2    0.158442
3    0.094801
4    0.221746
Name: Column: 01, dtype: float64

In [50]:
from pandas_datareader import data as wb

Apple = wb.DataReader('AAPL', data_source = 'yahoo', start = '1995-1-1')

Apple

High         Low        Open       Close        Volume  \
Date                                                                       
1995-01-03    0.347098    0.338170    0.347098    0.342634  1.038688e+08   
1995-01-04    0.353795    0.344866    0.344866    0.351563  1.586816e+08   
1995-01-05    0.351563    0.345982    0.350446    0.347098  7.364000e+07   
1995-01-06    0.385045    0.367188    0.371652    0.375000  1.076622e+09   
1995-01-09    0.373884    0.366071    0.371652    0.367885  2.740864e+08   
...                ...         ...         ...         ...           ...   
2022-06-01  151.740005  147.679993  149.899994  148.710007  7.428660e+07   
2022-06-02  151.270004  146.860001  147.830002  151.210007  7.234810e+07   
2022-06-03  147.970001  144.460007  146.899994  145.380005  8.847140e+07   
2022-06-06  148.570007  144.899994  147.029999  146.139999  7.159840e+07   
2022-06-07  148.990005  144.100006  144.345001  148.710007  6.691074e+07   

             Adj Close  
Date                    
1995-01-03    0.289652  
1995-01-04    0.297200  
1995-01-05    0.293425  
1995-01-06    0.317013  
1995-01-09    0.310998  
...                ...  
2022-06-01  148.710007  
2022-06-02  151.210007  
2022-06-03  145.380005  
2022-06-06  146.139999  
2022-06-07  148.710007  

[6907 rows x 6 columns]